site_name: Bergsspexet
site_url: https://bergsspexet.com

theme:
  name: material
  favicon: src/img/favicon.png
  logo: src/img/logo.png

  features:
  - navigation.indexes
  - navigation.tabs
  - navigation.top


  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - src/css/custom.css

plugins:
  - blog:
      blog_dir: aktuellt
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@bergsspexet1943
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/bergsspexet/
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@bergsspexet1943
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/Bergsspexet/
    - icon: fontawesome/solid/envelope
      link: /kontakt